### PR TITLE
FIX: Weapon stats accounting for perks

### PR DESCRIPTION
**Pull request by philipmat**
With deep apologies... 
This fixes an issue where the selected perks were not accounting for when displaying the weapon stats.

### CODE REVIEW

**Comment by phillipspc** [comment]
haha no problem @philipmat 
Also, related to the stats... It seems like after merging the Armor PR, a lot more of them are showing now (for weapons). Would you mind reverting it back to how it was initially (only showing primary/non-hidden stats)?

**Comment by philipmat** [comment]
Would you be ok with adding AA, Equip, and possibly Recoil to the base list? At least the first two are really important weapon stats.

**Comment by phillipspc** [comment]
I'm ok with AA and Equip as they are affected by your roll. Recoil, not so much.
But yeah, too many stats down there makes it looks cluttered, so I think thats the most I'd want. Also preferably they'd come after the rest, I liked that the order of the stats lined up with the bars you'd see when inspecting a weapon in game.

**Comment by philipmat** [comment]
Alright - thank you! I have a patch ready - I'll test it as soon as Bungie's API comes back online and push immediately after.

**Comment by philipmat** [comment]
Done and tested.
Also, you were right - it does look nicer with only the most relevant stats.

**Pull request merged**
